name: Run unit tests 
on:
  push:
    branches:
      - master
   
jobs:
  run-unit-tests-on-houston:
    runs-on: ubuntu-latest
    steps:
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-v7.72.0-697e9faee2-linux-x64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-cli-v7.72.0-697e9faee2-linux-x64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      - name: Run Apex Tests on Target Sandbox
        run: |
          sfdx --version
